x-healthcheck: &healthcheck_defaults
  interval: 10s
  timeout: 10s
  retries: 30
  start_period: 10s

x-snuba-defaults: &snuba_defaults
  image: getsentry/snuba:nightly
  environment:
    SNUBA_SETTINGS: "self_hosted"
    CLICKHOUSE_HOST: "clickhouse"
    DEFAULT_BROKERS: "kafka:9092"
    REDIS_HOST: "redis"
    UWSGI_MAX_REQUESTS: "10000"
    UWSGI_DISABLE_LOGGING: "true"
    # Leaving the value empty to just pass whatever is set
    # on the host system (or in the .env file)
    SENTRY_EVENT_RETENTION_DAYS: "${SENTRY_EVENT_RETENTION_DAYS:-90}"
  networks:
    - sentry
  deploy:
    rollback_config:
      parallelism: 1
      order: stop-first
      delay: 0s
      failure_action: rollback
      monitor: 0s
      max_failure_ratio: 1
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    update_config:
      parallelism: 1
      order: stop-first
      delay: 0s
      failure_action: rollback
      monitor: 0s
      max_failure_ratio: 1
    resources:
      limits:
        cpus: '0.2'
        memory: 512M

services:
  snuba-bootstrap:
    <<: *snuba_defaults
    command: bootstrap --no-migrate --force

  snuba-migrations:
    <<: *snuba_defaults
    command: migrations migrate --force
    depends_on:
      - snuba-bootstrap


networks:
  sentry:
    name: sentry
    external: true
