x-healthcheck: &healthcheck_defaults
  interval: 10s
  timeout: 10s
  retries: 30
  start_period: 10s

x-sentry-defaults: &sentry_defaults
  image: getsentry/sentry:nightly
  environment:
    PYTHONUSERBASE: "/data/custom-packages"
    SENTRY_CONF: "/etc/sentry"
    SNUBA: "http://snuba-api:1218"
    VROOM: "http://vroom:8085"
    # redis
    SENTRY_REDIS_HOST: "redis"
    # secret key
    SENTRY_SINGLE_ORGANIZATION: "false"
    SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY:-}"
    # Force everything to use the system CA bundle
    # This is mostly needed to support installing custom CA certs
    # This one is used by botocore
    DEFAULT_CA_BUNDLE: &ca_bundle "/etc/ssl/certs/ca-certificates.crt"
    # This one is used by requests
    REQUESTS_CA_BUNDLE: *ca_bundle
    # This one is used by grpc/google modules
    GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR: *ca_bundle
    # Leaving the value empty to just pass whatever is set
    # on the host system (or in the .env file)
    SENTRY_EVENT_RETENTION_DAYS: "${SENTRY_EVENT_RETENTION_DAYS:-90}"
    SENTRY_MAIL_HOST: "${SENTRY_MAIL_HOST:-}"
    SENTRY_MAX_EXTERNAL_SOURCEMAP_SIZE: "${SENTRY_MAX_EXTERNAL_SOURCEMAP_SIZE:-1M}"
    # Set this value if you plan on using the Suggested Fix Feature
    OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
    # Opt-out remote beacon server
    SENTRY_BEACON: "false"
  configs:
    - source: sentry.yml
      target: /etc/sentry/config.yml
    - source: sentry.conf.py
      target: /etc/sentry/sentry.conf.py
  networks:
    - sentry
  volumes:
    - sentry-data:/data
    - geoip:/geoip:ro
    - certificates:/usr/local/share/ca-certificates:ro
  deploy:
    rollback_config:
      parallelism: 1
      order: stop-first
      delay: 0s
      failure_action: rollback
      monitor: 0s
      max_failure_ratio: 1
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    update_config:
      parallelism: 1
      order: stop-first
      delay: 0s
      failure_action: rollback
      monitor: 0s
      max_failure_ratio: 1
    resources:
      limits:
        cpus: '0.25'
        memory: 1G

services:
  database-migration:
    <<: *sentry_defaults
    command: upgrade --noinput
    deploy:
      mode: replicated-job

networks:
  sentry:
    name: sentry
    external: true

configs:
  sentry.yml:
    file: configs/config.yml
  sentry.conf.py:
    file: configs/sentry.conf.py

volumes:
  sentry-data:

  # These are shared volumes from other services.
  geoip:
    name: geoip
    external: true
  certificates:
    name: certificates
    external: true
